# Generated by Django 2.0.2 on 2018-03-04 01:34

from django.db import migrations, models



def create_continent(apps, schema_editor):
    Country = apps.get_model("countries","Country")
    Continent = apps.get_model("continents", "Continent")

    countries_file = open(
        "/home/grupo-ari//manuel/practicas/programas/Python/django/geographic/data/country_n_continents", "r")

    while (True):
        countries_ = {}
        country = countries_file.readline()
        if country == '':
            break
        else:
            countries_['continent'], countries_['country'] = \
                country.replace('.json\n', '') \
                    .replace('./data/factbook.json/', '') \
                    .split('/', maxsplit=1)
            continent_db = Continent.objects.get(name=countries_['continent'])
            try:
                countries_db = Country.objects.get(code=countries_['country'])
            except:
                countries_db = Country.objects.get(code__regex=r'^' + countries_['country'] + '_.')
            countries_db.continent.add(continent_db)

class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_continent'),
    ]

    operations = [
        migrations.RunPython(create_continent),
    ]
