# Generated by Django 2.0.2 on 2018-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
